SELECT rest.REST_ID, rest.REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS rest
JOIN REST_REVIEW AS review
ON rest.REST_ID = review.REST_ID
WHERE rest.ADDRESS LIKE '서울%'
GROUP BY rest.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;